/'
    Project: OpenSesh
    ---------------------------

    File: tests/omagui_safety_smoke.bas

    Copyright (C) 2026 OpenSesh contributors
    SPDX-License-Identifier: GPL-3.0-or-later

    Targets: FreeBASIC fb dialect; Windows/Linux host test runners.
    Module API: Test executable; nonzero status reports a failed safety boundary.

    Purpose:

        Exercise GUI dependency boundaries changed during release preparation.

    Responsibilities:

        - reject bare CSS class and identifier prefixes
        - recognize an unallocated byte array without reading its data
        - preserve real editor text while rebuilding its masked display cache
        - retain label defaults and reject invalid or foreign-widget style writes
        - decode a bounded ICO image and reject every truncated prefix
        - reject unsupported LZX window sizes before allocating decoder state

    Ownership:

        This test owns and destroys its decoded image. The generated byte
        fixtures are local arrays. No window, device or user file is opened.

    This file intentionally does NOT contain:

        - a graphical desktop or timing benchmark
        - a general codec compatibility corpus
        - external images or copyrighted media fixtures
'/

#lang "fb"

#define OMAGUI_REDISTRIBUTABLE_FONTS
#define OMAGUI_IMPLEMENTATION
#include once "omaGUI.bi"

' -------------------------------------------------------------------------
' Assertion reporting
' -------------------------------------------------------------------------

Private Sub test_Fail(ByVal message As String)
    Print "FAIL omagui_safety: " & message
    backend_Exit()
    End 1
End Sub

' -------------------------------------------------------------------------
' Selector and empty-input boundaries
' -------------------------------------------------------------------------

' Screenless mode creates a temporary null-driver context only for image allocation.
backend_Init 1, 1, BACKEND_HEADLESS

If htmlview_CssSelectorMatches(".", "p", "") <> 0 Then _
    test_Fail "bare class selector matched empty attributes"
If htmlview_CssSelectorMatches("#", "p", "") <> 0 Then _
    test_Fail "bare identifier selector matched an empty identifier"
If htmlview_CssSelectorMatches("p", "p", "") = 0 Then _
    test_Fail "valid tag selector stopped matching"
If htmlview_CssSelectorMatches(".note", "p", "class=""note other""") = 0 Then _
    test_Fail "valid class selector stopped matching"
If htmlview_CssSelectorMatches("#note", "p", "id=""note""") = 0 Then _
    test_Fail "valid identifier selector stopped matching"

Dim As UByte emptyBytes()
If rasterimage_DetectFormat(emptyBytes(), 0) <> RASTERIMAGE_FORMAT_UNKNOWN Then _
    test_Fail "unallocated byte array was identified as an image"

' The derived view borrows this live, stack-owned editor state. Rebuilding the
' cache must leave real text intact and adjust when the input length changes.
Dim As TextBoxData maskState
maskState.text = "abcdef"
maskState.password_character = Asc("*") ' fblint: disable-line FBL-SEC-004 FBL008 REASON: This field selects a display glyph; no credential is stored.
If textbox_VisualText(@maskState) <> "******" Then _
    test_Fail "masked display does not match the input length"
If maskState.text <> "abcdef" Then test_Fail "masked display replaced real text"
maskState.text = "abc"
If textbox_VisualText(@maskState) <> "***" Then _
    test_Fail "masked display did not rebuild after a length change"

' -------------------------------------------------------------------------
' Label style defaults, bounds and ownership
' -------------------------------------------------------------------------

Dim As Widget Ptr styleLabel = label_Create("style-safety", "test", 0, 0)
If styleLabel = 0 Then test_Fail "label allocation failed"
If label_GetTextStyle(styleLabel) <> BACKEND_TEXT_STYLE_NORMAL Then _
    test_Fail "new label changed its original normal-text default"
If label_SetTextStyle(0, BACKEND_TEXT_STYLE_BOLD) <> 0 Then _
    test_Fail "label style setter accepted a null widget"
Dim As Widget foreignWidget
foreignWidget.data = @maskState
If label_SetTextStyle(@foreignWidget, BACKEND_TEXT_STYLE_BOLD) <> 0 Then _
    test_Fail "label style setter accepted another widget's data"
If label_SetTextStyle(styleLabel, BACKEND_TEXT_STYLE_ALL + 1) <> 0 Then _
    test_Fail "label style setter accepted undefined flags"
If label_GetTextStyle(styleLabel) <> BACKEND_TEXT_STYLE_NORMAL Then _
    test_Fail "invalid label style write changed state"
For styleFlags As Integer = BACKEND_TEXT_STYLE_NORMAL To BACKEND_TEXT_STYLE_ALL
    If label_SetTextStyle(styleLabel, styleFlags) = 0 Then _
        test_Fail "label rejected a supported style combination"
    If label_GetTextStyle(styleLabel) <> styleFlags Then _
        test_Fail "label did not retain its style flags"
    ' The headless one-pixel target also exercises bounded backend clipping.
    label_Render styleLabel
Next
label_Destroy styleLabel
Delete styleLabel
styleLabel = 0

' -------------------------------------------------------------------------
' Generated one-pixel ICO and truncated inputs
' -------------------------------------------------------------------------

/'
    ICO layout, all multi-byte fields little endian:

        0-5   : reserved=0, icon type=1, one directory entry
        6-21  : 1x1 image, one plane, 24 bits, payload length=48, offset=22
        22-61 : 40-byte DIB header, width=1, doubled height=2, RGB compression
        62-65 : BGR pixel (25,20,15) plus scanline padding
        66-69 : zero AND mask plus scanline padding

    The complete fixture is 70 bytes. Every shorter prefix must fail before
    pixels or a partial image can escape to the caller.
'/
Dim As UByte icoBytes(0 To 69)
icoBytes(2) = 1
icoBytes(4) = 1
icoBytes(6) = 1
icoBytes(7) = 1
icoBytes(10) = 1
icoBytes(12) = 24
icoBytes(14) = 48
icoBytes(18) = 22
icoBytes(22) = 40
icoBytes(26) = 1
icoBytes(30) = 2
icoBytes(34) = 1
icoBytes(36) = 24
icoBytes(62) = 25
icoBytes(63) = 20
icoBytes(64) = 15

Dim As RasterImage Ptr decodedImage
Dim As String errorText
For prefixLength As Integer = 0 To 69
    If rasterico_Decode(icoBytes(), prefixLength, decodedImage, errorText) <> 0 Then _
        test_Fail "truncated ICO input was accepted"
    If decodedImage <> 0 Then test_Fail "failed decode returned a partial image"
Next
If rasterico_Decode(icoBytes(), 70, decodedImage, errorText) = 0 Then _
    test_Fail "complete generated ICO was rejected: " & errorText
If decodedImage = 0 Then test_Fail "successful decode returned no image"
If decodedImage->width <> 1 OrElse decodedImage->height <> 1 Then _
    test_Fail "decoded ICO dimensions differ"
rasterimage_Destroy decodedImage

' -------------------------------------------------------------------------
' Unsupported LZX configuration
' -------------------------------------------------------------------------

Dim As String compressedText = Chr(0)
Dim As String outputText
If chmlzx_DecompressReset(compressedText, 1, 1, 1, outputText, errorText) <> 0 Then _
    test_Fail "unsupported LZX window was accepted"
If outputText <> "" Then test_Fail "failed LZX decode returned partial output"

Print "omagui_safety=ok"
Print "truncated_ico_rejections=70"
backend_Exit()
End 0

/' end of tests/omagui_safety_smoke.bas '/
